### ISSUE TITLE
Intersection type bugs meta-issue

### ISSUE THREAD

**Issue by samwgoldman** [facebook/flow#1331]
- [x] Intersection of object types should be a valid lower bound of the object type with properties from all branches (#1327)
- [ ] Support intersection of array type and object type (#1330)
- [x] Can't spread value with intersection-of-objects type (#1329)
- [x] Unable to refine variable type through intersection (#1325)

**Comment by machadogj** [comment]
Intersection types are awfully useful when working with react and passing down props from bigger components to smaller more specialised ones, however the lack of support for spread operator makes it very hard to work with (unless I'm missing something).

I noticed #1329 is "checked" and the issue has been closed in March. Does it mean it's been solved? If so, in which version/branch can we access this feature?

Thanks!

**Comment by machadogj** [comment]
Looks like one of the scenarios has been fixed in 0.50.0:
```
function bar(x: T): void {
  let z: T = { ...x }; // error - now fixed in 0.50.0
}
```

But the following seems to be problematic:

```
/* @flow */

type T = { foo: string } & { bar: number };

function bam({bar}: {bar: number}): number {
  return bar + 2;
}

function bar(x: T): void {
  let { foo, ...props } = x;
  bam(props); //error
}
```
Here's the reported error:
```
5: function bam({bar}: {bar: number}): number {
                       ^ property `bar`. Property not found in
11:   bam(props); //error
          ^ rest of object pattern
```

**Comment by gkz** [comment]
All sub-issues closed now
