### ISSUE TITLE
ES2015 & 2016 Features meta-issue

### ISSUE THREAD

**Issue by samwgoldman** [facebook/flow#560]
Feel free to open an issue for any unchecked feature that doesn't already have one, but please try to keep discussion in a single issue if possible. Use cases (and test cases) are very welcome!

To report a bug with a completed feature, please open a new issue for the bug.
### ES2015+
- [x] let/const declarations (#784)
- [x] Regular expression u flag (#2510)
- [x] Regular expression y flag
- [x] Binary literals (#566)
- [x] New octal literals (#566)
- [x] Arrow functions
- [x] Default parameters (mostly supported, except using `this`: #1234)
- [x] Rest parameters
- [x] Spread operator
- [x] super references
- [x] Classes
- [x] for-of loops
- [x] Generators (#534)
- [x] Object literal property shorthand
- [x] Object literal method shorthand
- [ ] Object literal computed properties (#252)
- [x] Template strings
- [x] Tagged templates
- [ ] Tagged template fn `strings` param has a `raw` prop
- [ ] Tagged template fn `strings` and `raw` arrays are frozen
- [x] Destructuring
- [x] Default values in destructuring (#183)
- [ ] Unicode code point escapes
- [x] Allow duplicate object literal properties (except **proto**)
- [x] Modules
- [x] [`new.target`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target) (#1152)
- [ ] Symbols (#810, #1015)
- [ ] `export Foo from 'foo'` (#2403)
- [x] object spread
- [x] async/await
- [x] async iterators (#1824)
- [ ] [Shared memory and atomics](https://github.com/tc39/ecmascript_sharedmem) (#7811)
- [ ] `String.prototype.matchAll` (#7812)
- [ ] `Promise.allSettled`
- [ ] [Lifting template literal restriction](https://github.com/tc39/proposal-template-literal-revision)

#### Stage 4
- [ ] [`String.prototype.replaceAll`](https://github.com/tc39/proposal-string-replaceall)

#### Stage 3
- [ ] [optional chaining](https://github.com/tc39/proposal-optional-chaining) (#4303)
- [ ] [`BigInt`](https://github.com/tc39/proposal-bigint) (#7602)
- [ ] [`globalThis`](https://github.com/tc39/proposal-global) (#7704)
- [ ] [`import.meta`](https://github.com/tc39/proposal-import-meta) (#6913)
- [x] [private instance methods and accessors](https://github.com/tc39/proposal-private-methods)
- [x] [nullish coalescing](https://github.com/tc39/proposal-nullish-coalescing) (#6257)
- [x] [class property initializers](https://github.com/tc39/proposal-class-fields) (#850)
- [x] [numeric separators](https://github.com/tc39/proposal-numeric-separator)
- [ ] [top-level `await`](https://github.com/tc39/proposal-top-level-await) (#7710)
- [ ] [`WeakRefs`](https://github.com/tc39/proposal-weakrefs)
- [ ] [RegExp Match array offsets](https://github.com/tc39/proposal-regexp-match-indices)
#### Stage 2
- [ ] [`Promise.any`](https://github.com/tc39/proposal-promise-any)
- [ ] [`function.sent`](https://github.com/allenwb/ESideas/blob/master/Generator%20metaproperty.md)
- [ ] [`throw` expressions](https://github.com/tc39/proposal-throw-expressions) (#6605)
- [ ] [`Atomics.waitAsync`](https://github.com/tc39/proposal-atomics-wait-async)
- [ ] [new `Set` methods](https://github.com/tc39/proposal-set-methods)
- [ ] [`ArrayBuffer.prototype.transfer`](https://github.com/domenic/proposal-arraybuffer-transfer/)
- [ ] [`Temporal`](https://github.com/tc39/proposal-temporal)
- [ ] [`Array.isTemplateObject`](https://github.com/tc39-transfer/proposal-array-is-template-object)
- [ ] [iterator helpers](https://github.com/tc39/proposal-iterator-helpers)
- [ ] [collection normalization](https://github.com/tc39-transfer/proposal-collection-normalization)
- [ ] [class decorators](https://github.com/tc39/proposal-decorators)
- [ ] [method decorators](https://github.com/tc39/proposal-decorators)
#### Stage 1
- [ ] [`do` expressions](https://github.com/tc39/proposal-do-expressions) (#2523)
- [ ] [`Emitter`](https://github.com/tc39/proposal-emitter)
- [ ] [pattern matching](https://github.com/tc39/proposal-pattern-matching) (#6353)
- [ ] [pipeline operator](https://github.com/tc39/proposal-pipeline-operator) (#5443)
#### Stage 0
- [ ] [function bind operator](https://github.com/tc39/proposal-bind-operator) (#1545)

**Comment by mroch** [comment]
this is super useful!

there are probably a bunch of new APIs that we need to add, too. for example, I just noticed that we don't have `String.prototype.codePointAt` (part of new unicode stuff)

**Comment by nmn** [comment]
Let/Const support is coming along nicely in #431 
Wanted to leave a reference to that here.

Also, perhaps, add an ES7 section and mark async-await as done.

(BTW, I find it surprising that async-await is done before generators!)

**Comment by Globegitter** [comment]
It seems there is an issue with ES6 Class support. I am using atom/nuclide IDE and having the following code:
```js
export default class Resource {
  constructor(req:string) {
    this.req = req * 2;
  }
}
```

`assignment of property req Property req not found in Resource` even though I am defining it here in the constructor.

**Comment by gabelevi** [comment]
@Globegitter, Flow wants you to declare class properties like so:

```JavaScript
export default class Resource {
  req: number;
  constructor(req: number) {
    this.req = req * 2;
  }
}
```

Why do we require this? Well, if we don't make people declare properties then we can't detect things like

```JavaScript
function getReq(resource: Resource): number {
  return resource.rep;
}
```

We do realize this is a little bit more work for the developer, but we're hoping the benefits outweigh the pain.

**Comment by Globegitter** [comment]
Aahh, I see, thanks @gabelevi For know I mostly want to use flow for its type inference with `/* @flow weak */`. The issue here is that I can not just put `req; res;` at the top, it does throw an 'Unexpected token;` issue.

Generally I do think this is an acceptable extra-effort, but why can flow not just get the information from the constructor itself? Is it that much more complex to see what `this.req` is assigned to and then look up the type in the constructor's parameter list?

As a side note kind of fitting to this, it would be great to see property initialiser support as mentioned here: http://babeljs.io/blog/2015/06/07/react-on-es6-plus/

**Comment by gabelevi** [comment]
I think at the moment that Flow requires type annotations for the class member properties you declare. So

```JavaScript
req: any; res: any;
```

should work. I did recently change the parsing of that (https://github.com/facebook/flow/commit/7e5b2a9a4bed89d97b5961b27d92a405f98f7b65) in preparation for class property initializers. We absolutely are planning support for class property initializers. They solve so many problems! The one I hate the most is how you have to do

```JavaScript
class Foo {
  constructor() {
    this.myCallBack = this.myCallBack.bind(this);
  }
  myCallBack() { ... }
}
```

but with class property initializers you can do

```JavaScript
class Foo {
  myCallBack = () => { ... }
}
```

**Comment by Globegitter** [comment]
Thanks for the quick response that all sounds good :) And yep it really does solve a lot of issues.

**Comment by samwgoldman** [comment]
> Generally I do think this is an acceptable extra-effort, but why can flow not just get the information from the constructor itself? Is it that much more complex to see what this.req is assigned to and then look up the type in the constructor's parameter list?

@Globegitter, good insight! Actually, flow used to do this, but the functionality was removed. I'm not sure about the details surrounding this, but there is some explanation in a [comment in the source code](https://github.com/facebook/flow/blob/229cbe470af7dbec79769c95c1040bc1ca3d2dbe/src/typing/type_inference_js.ml#L4769).

Unfortunately, this change was from the days of "sync to upstream" so the diff is big and it's hard to see the implications in terms of the code changes themselves.

**Comment by oztune** [comment]
![image](https://cloud.githubusercontent.com/assets/663175/8938673/077a99d6-352e-11e5-81b2-5ce48e3dfb6b.png)

^ What happened with `'let` support?

I think it'd help the project if this was taken care of if only because at a glance it makes the whole project seem to be behind. For example it's being used as a con on this list http://www.reddit.com/r/javascript/comments/39cere/typescript_vs_flow_results_from_our_investigation/

**Comment by samwgoldman** [comment]
> What happened with `let` support?

We're actively working on it. Please be patient.

**Comment by nmn** [comment]
@oztune by all means use my fork in the mean time: github.com/nmn/flow
- Up to date with flow itself
- Let/const support added by making flow treat them like var. (if you use Babel, the block scoping and const checking is already done for you)

**Comment by gregwebs** [comment]
classes are checked, but class property initializers are not supported: can we have a check box for that? Making it hard for me to swallow ES6 classes right now.

An alternative approach to much of this work is to [leverage babel more](https://github.com/babel/babel/issues/665)

**Comment by samwgoldman** [comment]
@gregwebs class property initializers are not ES6/ES2015, but it's definitely on our radar. I think, instead of creating a separate meta issue for ES2016 features, we should just track that here. I'll make the necessary changes.

**Comment by gregwebs** [comment]
Ah, in that case I will take any hack I can get. Seems to work to put this in the constructor:

``` javascript
      // fix broken es6 classes
      _.each(Object.getOwnPropertyNames( Object.getPrototypeOf(this) ), prop => {
        this[prop] = this[prop].bind(this)
      })
```

**Comment by Gozala** [comment]
@samwgoldman I think it would make sense to update #431 to  #784 given that's where the ongoing work is now.

**Comment by samwgoldman** [comment]
@Gozala You're right! Thanks & done.

**Comment by cesarandreu** [comment]
I'd vote for adding [export extensions](https://github.com/leebyron/ecmascript-more-export-from) to the ES2016 list. (Not sure if they're supported?)

**Comment by samwgoldman** [comment]
Is there an maintained list of the various proposals, along with the stage? Official would be ideal, but anything would help.

**Comment by cesarandreu** [comment]
@samwgoldman there's a [list](https://babeljs.io/docs/usage/experimental/) of the ones that are available in babel.

**Comment by BenoitZugmeyer** [comment]
@samwgoldman Here is the official list: https://github.com/tc39/ecma262

**Comment by tsing** [comment]
@samwgoldman I thinks the [`Reflect`](http://www.ecma-international.org/ecma-262/6.0/#sec-reflect-object) should be added to the list of ES2015

**Comment by friday** [comment]
That's not ES2015

**Comment by Gozala** [comment]
I think #810 should be on the list as well

**Comment by bolinfest** [comment]
@samwgoldman I just filed https://github.com/facebook/flow/issues/850 for ES7 property initializers, so could you please update this issue with that?

**Comment by RavenHursT** [comment]
What about ES6 Getters and Setters?  Currently Flow doesn't support the syntax, correct?

http://javascriptplayground.com/blog/2013/12/es5-getters-setters/

**Comment by hzoo** [comment]
@RavenHursT you can add `unsafe.enable_getters_and_setters=true` under `[options]` in your flowconfig

**Comment by RavenHursT** [comment]
@hzoo so looks like back in 0.14 they added what you're suggesting..  what does the `unsafe` denote?  Is this something we can use now in 0.16 and it'll work?

https://github.com/facebook/flow/releases/tag/v0.14.0

**Comment by samwgoldman** [comment]
@RavenHursT It's unsafe because a setter/getter might have a side-effect that causes a program to have a runtime error, but Flow won't catch it.

**Comment by RavenHursT** [comment]
@samwgoldman Got it.  Thanks! :+1:

**Comment by tsing** [comment]
@samwgoldman Could you add ES7 function bind syntax to the list ?
It is useful when use React ES6 classes

https://github.com/zenparsing/es-function-bind

**Comment by samwgoldman** [comment]
@tsing I'm not sure we should even track stage 0 (strawman) proposals. I'd like to see that proposal make a bit more standardization progress first.

**Comment by jrajav** [comment]
Is there already an issue for documentation somewhere? I don't know if it's supposed to be yet, but how to annotate arrow functions doesn't seem to be documented in http://flowtype.org/docs/functions.html.

**Comment by marudor** [comment]
List is outdated:
Class Decorator are fixed with https://github.com/facebook/flow/pull/1638
Regexp u and y flags with https://github.com/facebook/flow/pull/1177

**Comment by LikeJasper** [comment]
+1 for function bind operator

**Comment by vjau** [comment]
https://github.com/facebook/flow/issues/1732

**Comment by anaibol** [comment]
+1!

**Comment by rosskevin** [comment]
ES2015/2016 classes without semicolons break the parser and provide incorrect errors.  See #1908 with test repo included.

**Comment by rpominov** [comment]
Couldn't find class literal properties in the list. For example:

```js
class Id<T> {
  _x: T;
  constructor(x: T) {
    this._x = x
  }
  static 'fantasy-land/of'<T>(x: T): Id<T> {
    return new Id(x)
  }
}
```

Flow yields:

```
static 'fantasy-land/of'<T>(x: T): Id<T> {
       ^ literal properties not yet supported
```

Is this on agenda? We need it for [Fantasy Land](https://github.com/fantasyland/fantasy-land#prefixed-method-names) .

**Comment by yamafaktory** [comment]
Hi,

The **class decorators** feature is marked as checked but currently, those decorators are still not present in the AST (https://github.com/facebook/flow/pull/1638 & https://github.com/facebook/flow/issues/2741).

And thanks a lot for your great work 👍.

**Comment by Kovensky** [comment]
That is not some hack, that is the correct syntax (reexport the "default" export as an export named "default"). `export default from` is not valid syntax, but maybe the error message could be better.

**Comment by Pauan** [comment]
There is a proposal to add in this feature: [[link]](https://github.com/leebyron/ecmascript-export-default-from)

And a related proposal: [[link]](https://github.com/leebyron/ecmascript-export-ns-from)

**Comment by DimitryDushkin** [comment]
Thank you. I thought it's already in specification, because webpack 2 understands `export default from ...`.

**Comment by langri-sha** [comment]
`do` expressions are now stage 0. Here's is the list of active [ECMAScript proposals](https://github.com/tc39/proposals#ecmascript-proposals) for the curious.

**Comment by lyleunderwood** [comment]
`do` expressions are now stage 1.

**Comment by leoselig** [comment]
@samwgoldman I believe this

> - [ ] Default parameters (mostly supported, except using this: #1234)

is already done as of [this commit](https://github.com/facebook/flow/commit/d3887c226901cee0fad4d6058651c74e46bc3c14)

Is this list still maintained?

**Comment by grundiss** [comment]
Still no support for do-expressions? :C

**Comment by PinkaminaDianePie** [comment]
Any news about do-expressions? They are extremely useful for FP-style, but I can't use flow together with them.

**Comment by verekia** [comment]
Throw expressions: https://github.com/facebook/flow/issues/6605

**Comment by bradennapier** [comment]
do expressions ftw!

**Comment by bradennapier** [comment]
Came here to say "do expressions ftw!" but I see I already did this in July :-\ heh

**Comment by Xunnamius** [comment]
Not seeing flow errors for throw expressions would be incredibly nice!

**Comment by SPAHI4** [comment]
still waiting for do expressions

**Comment by goodmind** [comment]
@SPAHI4 it is not standard

**Comment by goodmind** [comment]
Updated list in post to reflect latest proposals

**Comment by fredericgermain** [comment]
I'd be very nice to have a status on import.meta (#6913)
@wchargin made a pull request a year ago and again two weeks ago, but @mroch in charge of it never commented. https://github.com/facebook/flow/pull/6958

**Comment by gkz** [comment]
This issue is old and no longer up to date. We can track the remaining features left in individual issues.

**Comment by noahehall** [comment]
@gkz there the top-level await issue is closed :(
