### ISSUE TITLE
typeof meta-issue

### ISSUE THREAD

**Issue by goodmind** [facebook/flow#7784]
- [ ] typeof annotation seems to parse incorrectly (https://github.com/facebook/flow/issues/2682)
- [ ] `typeof bool` error: unexpected typeof expression (https://github.com/facebook/flow/issues/3055)
- [ ] Unexpected reserved type in typeof _ (https://github.com/facebook/flow/issues/7461)

Babel can't do anything before Flow fixes this
https://github.com/babel/babel/issues/6701

**Comment by goodmind** [comment]
/cc @mroch @gabelevi 
@samwgoldman (we had this discussion in discord)

**Comment by SamChou19815** [comment]
All linked issues are fixed.
